// Code generated by protoc-gen-go.
// source: nlan.proto
// DO NOT EDIT!

/*
Package nlan is a generated protocol buffer package.

It is generated from these files:
	nlan.proto

It has these top-level messages:
	State
	Model
	Dvr
	Subnets
	IpDvr
	Vxlan
	Network
	L2Vpn
	Links
	Nodes
	Router
	Attrs
	Neighbor
	Ospf
	Vhosts
	VhostProps
*/
package nlan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type State struct {
	Router map[string]*Model `protobuf:"bytes,1,rep,name=Router" json:"Router,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *State) GetRouter() map[string]*Model {
	if m != nil {
		return m.Router
	}
	return nil
}

type Model struct {
	Dvr    *Dvr                `protobuf:"bytes,1,opt,name=Dvr" json:"Dvr,omitempty"`
	Ptn    map[string]*Network `protobuf:"bytes,2,rep,name=Ptn" json:"Ptn,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Router *Router             `protobuf:"bytes,3,opt,name=Router" json:"Router,omitempty"`
	Vhosts *Vhosts             `protobuf:"bytes,4,opt,name=Vhosts" json:"Vhosts,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Model) GetDvr() *Dvr {
	if m != nil {
		return m.Dvr
	}
	return nil
}

func (m *Model) GetPtn() map[string]*Network {
	if m != nil {
		return m.Ptn
	}
	return nil
}

func (m *Model) GetRouter() *Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Model) GetVhosts() *Vhosts {
	if m != nil {
		return m.Vhosts
	}
	return nil
}

type Dvr struct {
	OvsBridges bool       `protobuf:"varint,1,opt,name=OvsBridges" json:"OvsBridges,omitempty"`
	Subnets    []*Subnets `protobuf:"bytes,2,rep,name=Subnets" json:"Subnets,omitempty"`
	Vxlan      []*Vxlan   `protobuf:"bytes,3,rep,name=Vxlan" json:"Vxlan,omitempty"`
}

func (m *Dvr) Reset()                    { *m = Dvr{} }
func (m *Dvr) String() string            { return proto.CompactTextString(m) }
func (*Dvr) ProtoMessage()               {}
func (*Dvr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Dvr) GetSubnets() []*Subnets {
	if m != nil {
		return m.Subnets
	}
	return nil
}

func (m *Dvr) GetVxlan() []*Vxlan {
	if m != nil {
		return m.Vxlan
	}
	return nil
}

type Subnets struct {
	IpDvr []*IpDvr `protobuf:"bytes,1,rep,name=IpDvr" json:"IpDvr,omitempty"`
	Peers []string `protobuf:"bytes,2,rep,name=Peers" json:"Peers,omitempty"`
	Ports []string `protobuf:"bytes,3,rep,name=Ports" json:"Ports,omitempty"`
	Vid   uint32   `protobuf:"varint,4,opt,name=Vid" json:"Vid,omitempty"`
	Vni   uint32   `protobuf:"varint,5,opt,name=Vni" json:"Vni,omitempty"`
}

func (m *Subnets) Reset()                    { *m = Subnets{} }
func (m *Subnets) String() string            { return proto.CompactTextString(m) }
func (*Subnets) ProtoMessage()               {}
func (*Subnets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Subnets) GetIpDvr() []*IpDvr {
	if m != nil {
		return m.IpDvr
	}
	return nil
}

type IpDvr struct {
	Addr string `protobuf:"bytes,1,opt,name=Addr" json:"Addr,omitempty"`
	Dhcp string `protobuf:"bytes,2,opt,name=Dhcp" json:"Dhcp,omitempty"`
	Mode string `protobuf:"bytes,3,opt,name=Mode" json:"Mode,omitempty"`
}

func (m *IpDvr) Reset()                    { *m = IpDvr{} }
func (m *IpDvr) String() string            { return proto.CompactTextString(m) }
func (*IpDvr) ProtoMessage()               {}
func (*IpDvr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Vxlan struct {
	LocalIp   string   `protobuf:"bytes,1,opt,name=LocalIp" json:"LocalIp,omitempty"`
	RemoteIps []string `protobuf:"bytes,2,rep,name=RemoteIps" json:"RemoteIps,omitempty"`
}

func (m *Vxlan) Reset()                    { *m = Vxlan{} }
func (m *Vxlan) String() string            { return proto.CompactTextString(m) }
func (*Vxlan) ProtoMessage()               {}
func (*Vxlan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Network struct {
	L2Vpn []*L2Vpn `protobuf:"bytes,2,rep,name=L2Vpn" json:"L2Vpn,omitempty"`
	Links *Links   `protobuf:"bytes,3,opt,name=Links" json:"Links,omitempty"`
	Nodes *Nodes   `protobuf:"bytes,4,opt,name=Nodes" json:"Nodes,omitempty"`
}

func (m *Network) Reset()                    { *m = Network{} }
func (m *Network) String() string            { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()               {}
func (*Network) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Network) GetL2Vpn() []*L2Vpn {
	if m != nil {
		return m.L2Vpn
	}
	return nil
}

func (m *Network) GetLinks() *Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Network) GetNodes() *Nodes {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type L2Vpn struct {
	Ip    string   `protobuf:"bytes,1,opt,name=Ip" json:"Ip,omitempty"`
	Peers []string `protobuf:"bytes,2,rep,name=Peers" json:"Peers,omitempty"`
	Vid   uint32   `protobuf:"varint,3,opt,name=Vid" json:"Vid,omitempty"`
	Vni   uint32   `protobuf:"varint,4,opt,name=Vni" json:"Vni,omitempty"`
}

func (m *L2Vpn) Reset()                    { *m = L2Vpn{} }
func (m *L2Vpn) String() string            { return proto.CompactTextString(m) }
func (*L2Vpn) ProtoMessage()               {}
func (*L2Vpn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Links struct {
	LocalIp   string   `protobuf:"bytes,1,opt,name=LocalIp" json:"LocalIp,omitempty"`
	RemoteIps []string `protobuf:"bytes,2,rep,name=RemoteIps" json:"RemoteIps,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Nodes struct {
	L2Sw string `protobuf:"bytes,1,opt,name=L2Sw" json:"L2Sw,omitempty"`
	Ptn  string `protobuf:"bytes,2,opt,name=Ptn" json:"Ptn,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Router struct {
	Bgp         map[string]*Attrs `protobuf:"bytes,1,rep,name=Bgp" json:"Bgp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmbeddedBgp bool              `protobuf:"varint,2,opt,name=EmbeddedBgp" json:"EmbeddedBgp,omitempty"`
	Loopback    string            `protobuf:"bytes,3,opt,name=Loopback" json:"Loopback,omitempty"`
	Ospf        []*Ospf           `protobuf:"bytes,4,rep,name=Ospf" json:"Ospf,omitempty"`
}

func (m *Router) Reset()                    { *m = Router{} }
func (m *Router) String() string            { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()               {}
func (*Router) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Router) GetBgp() map[string]*Attrs {
	if m != nil {
		return m.Bgp
	}
	return nil
}

func (m *Router) GetOspf() []*Ospf {
	if m != nil {
		return m.Ospf
	}
	return nil
}

type Attrs struct {
	Neighbors []*Neighbor `protobuf:"bytes,1,rep,name=Neighbors" json:"Neighbors,omitempty"`
}

func (m *Attrs) Reset()                    { *m = Attrs{} }
func (m *Attrs) String() string            { return proto.CompactTextString(m) }
func (*Attrs) ProtoMessage()               {}
func (*Attrs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Attrs) GetNeighbors() []*Neighbor {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type Neighbor struct {
	NextHopSelf          bool   `protobuf:"varint,1,opt,name=NextHopSelf" json:"NextHopSelf,omitempty"`
	Peer                 string `protobuf:"bytes,2,opt,name=Peer" json:"Peer,omitempty"`
	RemoteAs             uint32 `protobuf:"varint,3,opt,name=RemoteAs" json:"RemoteAs,omitempty"`
	RouteReflectorClient bool   `protobuf:"varint,4,opt,name=RouteReflectorClient" json:"RouteReflectorClient,omitempty"`
}

func (m *Neighbor) Reset()                    { *m = Neighbor{} }
func (m *Neighbor) String() string            { return proto.CompactTextString(m) }
func (*Neighbor) ProtoMessage()               {}
func (*Neighbor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type Ospf struct {
	Area     string   `protobuf:"bytes,1,opt,name=Area" json:"Area,omitempty"`
	Networks []string `protobuf:"bytes,2,rep,name=Networks" json:"Networks,omitempty"`
}

func (m *Ospf) Reset()                    { *m = Ospf{} }
func (m *Ospf) String() string            { return proto.CompactTextString(m) }
func (*Ospf) ProtoMessage()               {}
func (*Ospf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type Vhosts struct {
	VhostProps []*VhostProps `protobuf:"bytes,1,rep,name=VhostProps" json:"VhostProps,omitempty"`
}

func (m *Vhosts) Reset()                    { *m = Vhosts{} }
func (m *Vhosts) String() string            { return proto.CompactTextString(m) }
func (*Vhosts) ProtoMessage()               {}
func (*Vhosts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Vhosts) GetVhostProps() []*VhostProps {
	if m != nil {
		return m.VhostProps
	}
	return nil
}

type VhostProps struct {
	Network string `protobuf:"bytes,1,opt,name=Network" json:"Network,omitempty"`
	Vhosts  uint32 `protobuf:"varint,2,opt,name=Vhosts" json:"Vhosts,omitempty"`
}

func (m *VhostProps) Reset()                    { *m = VhostProps{} }
func (m *VhostProps) String() string            { return proto.CompactTextString(m) }
func (*VhostProps) ProtoMessage()               {}
func (*VhostProps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*State)(nil), "nlan.State")
	proto.RegisterType((*Model)(nil), "nlan.Model")
	proto.RegisterType((*Dvr)(nil), "nlan.Dvr")
	proto.RegisterType((*Subnets)(nil), "nlan.Subnets")
	proto.RegisterType((*IpDvr)(nil), "nlan.IpDvr")
	proto.RegisterType((*Vxlan)(nil), "nlan.Vxlan")
	proto.RegisterType((*Network)(nil), "nlan.Network")
	proto.RegisterType((*L2Vpn)(nil), "nlan.L2Vpn")
	proto.RegisterType((*Links)(nil), "nlan.Links")
	proto.RegisterType((*Nodes)(nil), "nlan.Nodes")
	proto.RegisterType((*Router)(nil), "nlan.Router")
	proto.RegisterType((*Attrs)(nil), "nlan.Attrs")
	proto.RegisterType((*Neighbor)(nil), "nlan.Neighbor")
	proto.RegisterType((*Ospf)(nil), "nlan.Ospf")
	proto.RegisterType((*Vhosts)(nil), "nlan.Vhosts")
	proto.RegisterType((*VhostProps)(nil), "nlan.VhostProps")
}

var fileDescriptor0 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x56, 0xe2, 0xb8, 0xb5, 0xc7, 0x4d, 0x7f, 0xfd, 0x2d, 0x05, 0xa2, 0xa8, 0x42, 0x60, 0x21,
	0xa8, 0x40, 0x58, 0x22, 0x1c, 0x80, 0x8a, 0x4b, 0x4b, 0x2b, 0x51, 0x29, 0xa4, 0x55, 0x23, 0x72,
	0xe3, 0xe0, 0xc4, 0x9b, 0xc4, 0x8a, 0xeb, 0xb5, 0xd6, 0x9b, 0xb4, 0x7d, 0x21, 0xde, 0x81, 0xb7,
	0x63, 0x77, 0x76, 0x6c, 0x5c, 0x4e, 0xbd, 0x79, 0xbe, 0xf9, 0xf7, 0xcd, 0x37, 0xb3, 0x06, 0xc8,
	0xb3, 0x38, 0x8f, 0x0a, 0x29, 0x94, 0x60, 0x1d, 0xf3, 0x1d, 0x66, 0xe0, 0x8e, 0x55, 0xac, 0x38,
	0x7b, 0x0d, 0x5b, 0x57, 0x62, 0xad, 0xb8, 0xec, 0xb5, 0x9e, 0x3b, 0x87, 0xc1, 0xe0, 0x69, 0x84,
	0xb1, 0xe8, 0x8c, 0xac, 0xe7, 0x2c, 0x57, 0xf2, 0xae, 0x7f, 0x04, 0x41, 0xc3, 0x64, 0x01, 0x38,
	0x2b, 0x7e, 0xa7, 0x93, 0x5a, 0x87, 0x3e, 0xeb, 0x83, 0xbb, 0x89, 0xb3, 0x35, 0xef, 0xb5, 0xb5,
	0x19, 0x0c, 0x02, 0x5b, 0xe3, 0xbb, 0x48, 0x78, 0x76, 0xd4, 0xfe, 0xd4, 0x0a, 0x7f, 0xb7, 0xc0,
	0x45, 0x8b, 0x3d, 0x01, 0xe7, 0x74, 0x23, 0x31, 0x2d, 0x18, 0xf8, 0x36, 0x4e, 0x03, 0xec, 0x05,
	0x38, 0x97, 0x2a, 0xd7, 0xf9, 0x86, 0xc3, 0x7e, 0x23, 0x3f, 0xd2, 0xb0, 0xed, 0x78, 0x50, 0x33,
	0x75, 0x30, 0x7b, 0xc7, 0x46, 0x59, 0xcc, 0x78, 0x27, 0x4b, 0x51, 0xaa, 0xb2, 0xd7, 0x69, 0x7a,
	0x2d, 0xd6, 0xff, 0x0c, 0x5e, 0x5d, 0xe7, 0x1e, 0xf3, 0x83, 0xfb, 0xcc, 0xbb, 0x36, 0x6b, 0xc4,
	0xd5, 0x8d, 0x90, 0x2b, 0xe4, 0xfe, 0x03, 0x19, 0x33, 0x06, 0x70, 0xb1, 0x29, 0x4f, 0x64, 0x9a,
	0x2c, 0x78, 0x89, 0xc9, 0x1e, 0x7b, 0x06, 0xdb, 0xe3, 0xf5, 0x34, 0xe7, 0xba, 0xa9, 0x25, 0x4e,
	0xe9, 0x04, 0x1a, 0x59, 0x26, 0xb7, 0x1a, 0xd0, 0x84, 0x9d, 0xbf, 0xb2, 0x20, 0x14, 0xfe, 0xac,
	0x73, 0x4d, 0xd8, 0x79, 0x61, 0x55, 0x69, 0x84, 0x21, 0xc4, 0xba, 0xe0, 0x5e, 0x72, 0x2e, 0x6d,
	0x03, 0x1f, 0x4d, 0x21, 0x75, 0x3f, 0x07, 0x4d, 0x3d, 0xca, 0x24, 0x4d, 0x70, 0xe2, 0x2e, 0x1a,
	0x79, 0xda, 0x73, 0x8d, 0x11, 0xbe, 0xa7, 0x9a, 0x6c, 0x07, 0x3a, 0xc7, 0x49, 0x22, 0x69, 0x5c,
	0x6d, 0x9d, 0x2e, 0x67, 0x05, 0x4e, 0x8b, 0x96, 0xd1, 0x18, 0xf5, 0xf4, 0xc3, 0xb7, 0xc4, 0x96,
	0xfd, 0x07, 0xdb, 0x43, 0x31, 0x8b, 0xb3, 0xf3, 0x82, 0xb2, 0xfe, 0x07, 0xff, 0x8a, 0x5f, 0x0b,
	0xc5, 0xcf, 0x0b, 0x22, 0x62, 0xe8, 0x93, 0x48, 0x86, 0xfe, 0x70, 0x30, 0x29, 0xaa, 0xe5, 0x11,
	0x7d, 0x84, 0xd0, 0x97, 0xe6, 0xab, 0x92, 0x56, 0x56, 0xf9, 0x0c, 0x64, 0x7c, 0x23, 0xdd, 0xbd,
	0x5a, 0x18, 0xf9, 0x10, 0x0a, 0xbf, 0x50, 0x4d, 0xad, 0x7a, 0xbb, 0xa6, 0xf1, 0x8f, 0x16, 0x34,
	0xbc, 0xd3, 0x1c, 0x1e, 0x95, 0x30, 0x93, 0xd8, 0x16, 0x0f, 0x99, 0x24, 0x24, 0x1a, 0x46, 0x8d,
	0xe1, 0x60, 0x7c, 0x43, 0x91, 0x41, 0x75, 0x90, 0x46, 0x9a, 0x5f, 0xad, 0xea, 0xf6, 0x58, 0x08,
	0xce, 0xc9, 0xa2, 0xa0, 0x55, 0x3d, 0x6e, 0x9e, 0x60, 0xa4, 0x71, 0x7b, 0x61, 0x8f, 0x20, 0x38,
	0xbb, 0x9e, 0xf2, 0x24, 0xe1, 0x89, 0x89, 0x6d, 0xe3, 0xb1, 0xec, 0x81, 0x37, 0x14, 0xa2, 0x98,
	0xc6, 0xb3, 0x95, 0x15, 0x9c, 0xf5, 0xa0, 0x73, 0x51, 0x16, 0x73, 0x4d, 0xda, 0xd4, 0x02, 0x5b,
	0xcb, 0x20, 0xfd, 0x8f, 0xe0, 0xd5, 0xc5, 0x1e, 0xf0, 0xd0, 0x8e, 0x95, 0x92, 0x25, 0x1e, 0xeb,
	0x1b, 0x70, 0xd1, 0xd0, 0xef, 0xc9, 0x1f, 0xf1, 0x74, 0xb1, 0x9c, 0x0a, 0x59, 0x12, 0xd9, 0xdd,
	0xea, 0xb6, 0x2d, 0xac, 0x57, 0xe8, 0x55, 0xdf, 0x86, 0xf1, 0x88, 0xdf, 0xaa, 0x6f, 0xa2, 0x18,
	0xf3, 0x6c, 0x4e, 0xe7, 0xad, 0x05, 0x31, 0x7a, 0xd3, 0xb1, 0x68, 0xfe, 0x56, 0xba, 0xe3, 0x92,
	0x34, 0x3f, 0x80, 0x7d, 0x9c, 0xfc, 0x8a, 0xcf, 0x33, 0x3e, 0x53, 0x42, 0x7e, 0xcd, 0x52, 0x9e,
	0x2b, 0x5c, 0x82, 0x17, 0xbe, 0xb2, 0xd3, 0xe1, 0x01, 0x4a, 0x1e, 0xd3, 0x00, 0x7b, 0xa6, 0x29,
	0xde, 0x4d, 0xa5, 0x7f, 0x54, 0x3d, 0x5c, 0xf6, 0x12, 0x00, 0xbf, 0x2e, 0xa5, 0x28, 0x2a, 0xd2,
	0x7b, 0x8d, 0x67, 0x8c, 0x78, 0xf8, 0xae, 0x19, 0x65, 0x36, 0x4c, 0xf5, 0xa8, 0xc1, 0x6e, 0xfd,
	0x1f, 0x30, 0xb4, 0xbb, 0xd3, 0x2d, 0xfc, 0xeb, 0x7d, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbb,
	0x40, 0x9b, 0x76, 0x03, 0x05, 0x00, 0x00,
}
