// Code generated by protoc-gen-go.
// source: nlan.proto
// DO NOT EDIT!

/*
Package nlan is a generated protocol buffer package.

It is generated from these files:
	nlan.proto

It has these top-level messages:
	Model
	Dvr
	Subnets
	IpDvr
	Vxlan
	Ptn
	Networks
	L2Vpn
	Links
	Nodes
	Router
	Bgp
	Neighbors
	Ospf
	Vhosts
	VhostProps
*/
package nlan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Model struct {
	Dvr    *Dvr    `protobuf:"bytes,1,opt,name=Dvr" json:"Dvr,omitempty"`
	Ptn    *Ptn    `protobuf:"bytes,2,opt,name=Ptn" json:"Ptn,omitempty"`
	Router *Router `protobuf:"bytes,3,opt,name=Router" json:"Router,omitempty"`
	Vhosts *Vhosts `protobuf:"bytes,4,opt,name=Vhosts" json:"Vhosts,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Model) GetDvr() *Dvr {
	if m != nil {
		return m.Dvr
	}
	return nil
}

func (m *Model) GetPtn() *Ptn {
	if m != nil {
		return m.Ptn
	}
	return nil
}

func (m *Model) GetRouter() *Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Model) GetVhosts() *Vhosts {
	if m != nil {
		return m.Vhosts
	}
	return nil
}

type Dvr struct {
	OvsBridges bool       `protobuf:"varint,1,opt,name=OvsBridges" json:"OvsBridges,omitempty"`
	Subnets    []*Subnets `protobuf:"bytes,2,rep,name=Subnets" json:"Subnets,omitempty"`
	Vxlan      []*Vxlan   `protobuf:"bytes,3,rep,name=Vxlan" json:"Vxlan,omitempty"`
}

func (m *Dvr) Reset()                    { *m = Dvr{} }
func (m *Dvr) String() string            { return proto.CompactTextString(m) }
func (*Dvr) ProtoMessage()               {}
func (*Dvr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Dvr) GetSubnets() []*Subnets {
	if m != nil {
		return m.Subnets
	}
	return nil
}

func (m *Dvr) GetVxlan() []*Vxlan {
	if m != nil {
		return m.Vxlan
	}
	return nil
}

type Subnets struct {
	IpDvr []*IpDvr `protobuf:"bytes,1,rep,name=IpDvr" json:"IpDvr,omitempty"`
	Peers []string `protobuf:"bytes,2,rep,name=Peers" json:"Peers,omitempty"`
	Ports []string `protobuf:"bytes,3,rep,name=Ports" json:"Ports,omitempty"`
	Vid   uint32   `protobuf:"varint,4,opt,name=Vid" json:"Vid,omitempty"`
	Vni   uint32   `protobuf:"varint,5,opt,name=Vni" json:"Vni,omitempty"`
}

func (m *Subnets) Reset()                    { *m = Subnets{} }
func (m *Subnets) String() string            { return proto.CompactTextString(m) }
func (*Subnets) ProtoMessage()               {}
func (*Subnets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Subnets) GetIpDvr() []*IpDvr {
	if m != nil {
		return m.IpDvr
	}
	return nil
}

type IpDvr struct {
	Addr string `protobuf:"bytes,1,opt,name=Addr" json:"Addr,omitempty"`
	Dhcp string `protobuf:"bytes,2,opt,name=Dhcp" json:"Dhcp,omitempty"`
	Mode string `protobuf:"bytes,3,opt,name=Mode" json:"Mode,omitempty"`
}

func (m *IpDvr) Reset()                    { *m = IpDvr{} }
func (m *IpDvr) String() string            { return proto.CompactTextString(m) }
func (*IpDvr) ProtoMessage()               {}
func (*IpDvr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Vxlan struct {
	LocalIp   string   `protobuf:"bytes,1,opt,name=LocalIp" json:"LocalIp,omitempty"`
	RemoteIps []string `protobuf:"bytes,2,rep,name=RemoteIps" json:"RemoteIps,omitempty"`
}

func (m *Vxlan) Reset()                    { *m = Vxlan{} }
func (m *Vxlan) String() string            { return proto.CompactTextString(m) }
func (*Vxlan) ProtoMessage()               {}
func (*Vxlan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Ptn struct {
	Networks []*Networks `protobuf:"bytes,1,rep,name=Networks" json:"Networks,omitempty"`
}

func (m *Ptn) Reset()                    { *m = Ptn{} }
func (m *Ptn) String() string            { return proto.CompactTextString(m) }
func (*Ptn) ProtoMessage()               {}
func (*Ptn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Ptn) GetNetworks() []*Networks {
	if m != nil {
		return m.Networks
	}
	return nil
}

type Networks struct {
	Id    string   `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	L2Vpn []*L2Vpn `protobuf:"bytes,2,rep,name=L2Vpn" json:"L2Vpn,omitempty"`
	Links *Links   `protobuf:"bytes,3,opt,name=Links" json:"Links,omitempty"`
	Nodes *Nodes   `protobuf:"bytes,4,opt,name=Nodes" json:"Nodes,omitempty"`
}

func (m *Networks) Reset()                    { *m = Networks{} }
func (m *Networks) String() string            { return proto.CompactTextString(m) }
func (*Networks) ProtoMessage()               {}
func (*Networks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Networks) GetL2Vpn() []*L2Vpn {
	if m != nil {
		return m.L2Vpn
	}
	return nil
}

func (m *Networks) GetLinks() *Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Networks) GetNodes() *Nodes {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type L2Vpn struct {
	Ip    string   `protobuf:"bytes,1,opt,name=Ip" json:"Ip,omitempty"`
	Peers []string `protobuf:"bytes,2,rep,name=Peers" json:"Peers,omitempty"`
	Vid   uint32   `protobuf:"varint,3,opt,name=Vid" json:"Vid,omitempty"`
	Vni   uint32   `protobuf:"varint,4,opt,name=Vni" json:"Vni,omitempty"`
}

func (m *L2Vpn) Reset()                    { *m = L2Vpn{} }
func (m *L2Vpn) String() string            { return proto.CompactTextString(m) }
func (*L2Vpn) ProtoMessage()               {}
func (*L2Vpn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Links struct {
	LocalIp   string   `protobuf:"bytes,1,opt,name=LocalIp" json:"LocalIp,omitempty"`
	RemoteIps []string `protobuf:"bytes,2,rep,name=RemoteIps" json:"RemoteIps,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Nodes struct {
	L2Sw string `protobuf:"bytes,1,opt,name=L2Sw" json:"L2Sw,omitempty"`
	Ptn  string `protobuf:"bytes,2,opt,name=Ptn" json:"Ptn,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Router struct {
	Bgp         []*Bgp  `protobuf:"bytes,1,rep,name=Bgp" json:"Bgp,omitempty"`
	EmbeddedBgp bool    `protobuf:"varint,2,opt,name=EmbeddedBgp" json:"EmbeddedBgp,omitempty"`
	Loopback    string  `protobuf:"bytes,3,opt,name=Loopback" json:"Loopback,omitempty"`
	Ospf        []*Ospf `protobuf:"bytes,4,rep,name=Ospf" json:"Ospf,omitempty"`
}

func (m *Router) Reset()                    { *m = Router{} }
func (m *Router) String() string            { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()               {}
func (*Router) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Router) GetBgp() []*Bgp {
	if m != nil {
		return m.Bgp
	}
	return nil
}

func (m *Router) GetOspf() []*Ospf {
	if m != nil {
		return m.Ospf
	}
	return nil
}

type Bgp struct {
	As        uint32       `protobuf:"varint,1,opt,name=As" json:"As,omitempty"`
	Neighbors []*Neighbors `protobuf:"bytes,2,rep,name=Neighbors" json:"Neighbors,omitempty"`
}

func (m *Bgp) Reset()                    { *m = Bgp{} }
func (m *Bgp) String() string            { return proto.CompactTextString(m) }
func (*Bgp) ProtoMessage()               {}
func (*Bgp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Bgp) GetNeighbors() []*Neighbors {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type Neighbors struct {
	NextHopSelf          bool   `protobuf:"varint,1,opt,name=NextHopSelf" json:"NextHopSelf,omitempty"`
	Peer                 string `protobuf:"bytes,2,opt,name=Peer" json:"Peer,omitempty"`
	RemoteAs             uint32 `protobuf:"varint,3,opt,name=RemoteAs" json:"RemoteAs,omitempty"`
	RouteReflectorClient bool   `protobuf:"varint,4,opt,name=RouteReflectorClient" json:"RouteReflectorClient,omitempty"`
}

func (m *Neighbors) Reset()                    { *m = Neighbors{} }
func (m *Neighbors) String() string            { return proto.CompactTextString(m) }
func (*Neighbors) ProtoMessage()               {}
func (*Neighbors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type Ospf struct {
	Area     string   `protobuf:"bytes,1,opt,name=Area" json:"Area,omitempty"`
	Networks []string `protobuf:"bytes,2,rep,name=Networks" json:"Networks,omitempty"`
}

func (m *Ospf) Reset()                    { *m = Ospf{} }
func (m *Ospf) String() string            { return proto.CompactTextString(m) }
func (*Ospf) ProtoMessage()               {}
func (*Ospf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type Vhosts struct {
	VhostProps []*VhostProps `protobuf:"bytes,1,rep,name=VhostProps" json:"VhostProps,omitempty"`
}

func (m *Vhosts) Reset()                    { *m = Vhosts{} }
func (m *Vhosts) String() string            { return proto.CompactTextString(m) }
func (*Vhosts) ProtoMessage()               {}
func (*Vhosts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Vhosts) GetVhostProps() []*VhostProps {
	if m != nil {
		return m.VhostProps
	}
	return nil
}

type VhostProps struct {
	Network string `protobuf:"bytes,1,opt,name=Network" json:"Network,omitempty"`
	Vhosts  uint32 `protobuf:"varint,2,opt,name=Vhosts" json:"Vhosts,omitempty"`
}

func (m *VhostProps) Reset()                    { *m = VhostProps{} }
func (m *VhostProps) String() string            { return proto.CompactTextString(m) }
func (*VhostProps) ProtoMessage()               {}
func (*VhostProps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*Model)(nil), "nlan.Model")
	proto.RegisterType((*Dvr)(nil), "nlan.Dvr")
	proto.RegisterType((*Subnets)(nil), "nlan.Subnets")
	proto.RegisterType((*IpDvr)(nil), "nlan.IpDvr")
	proto.RegisterType((*Vxlan)(nil), "nlan.Vxlan")
	proto.RegisterType((*Ptn)(nil), "nlan.Ptn")
	proto.RegisterType((*Networks)(nil), "nlan.Networks")
	proto.RegisterType((*L2Vpn)(nil), "nlan.L2Vpn")
	proto.RegisterType((*Links)(nil), "nlan.Links")
	proto.RegisterType((*Nodes)(nil), "nlan.Nodes")
	proto.RegisterType((*Router)(nil), "nlan.Router")
	proto.RegisterType((*Bgp)(nil), "nlan.Bgp")
	proto.RegisterType((*Neighbors)(nil), "nlan.Neighbors")
	proto.RegisterType((*Ospf)(nil), "nlan.Ospf")
	proto.RegisterType((*Vhosts)(nil), "nlan.Vhosts")
	proto.RegisterType((*VhostProps)(nil), "nlan.VhostProps")
}

var fileDescriptor0 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6b, 0xdb, 0x4e,
	0x10, 0x25, 0x96, 0x9d, 0x58, 0xe3, 0x38, 0xf1, 0x6f, 0x7f, 0xa5, 0x88, 0x12, 0x8a, 0x59, 0x4a,
	0x5b, 0x28, 0x35, 0xd4, 0xa5, 0xb7, 0x5e, 0x9c, 0xa6, 0x50, 0x83, 0xeb, 0x18, 0x9b, 0xfa, 0xd6,
	0x82, 0x64, 0xad, 0x6d, 0xd5, 0x8a, 0x76, 0x59, 0x29, 0x1f, 0x7f, 0x7e, 0x77, 0x66, 0x47, 0x89,
	0xe8, 0xa9, 0x37, 0xcf, 0x9b, 0xaf, 0x37, 0x6f, 0x9f, 0x0c, 0x50, 0xe4, 0x71, 0x31, 0x32, 0x56,
	0x57, 0x5a, 0xb4, 0xf1, 0xb7, 0x2c, 0xa1, 0xf3, 0x5d, 0xa7, 0x2a, 0x17, 0xcf, 0x21, 0xb8, 0xba,
	0xb3, 0xd1, 0xd1, 0xf0, 0xe8, 0x6d, 0x6f, 0x1c, 0x8e, 0xa8, 0xd0, 0x01, 0x88, 0x2f, 0xaa, 0x22,
	0x6a, 0x35, 0x71, 0x07, 0x88, 0x0b, 0x38, 0x5e, 0xea, 0xdb, 0x4a, 0xd9, 0x28, 0xa0, 0xd4, 0xa9,
	0x4f, 0x79, 0x0c, 0xb3, 0xeb, 0xbd, 0x2e, 0xab, 0x32, 0x6a, 0x37, 0xb3, 0x1e, 0x93, 0x3f, 0x68,
	0x97, 0x10, 0x00, 0xd7, 0x77, 0xe5, 0xa5, 0xcd, 0xd2, 0x9d, 0x2a, 0x69, 0x73, 0x57, 0xbc, 0x84,
	0x93, 0xd5, 0x6d, 0x52, 0x28, 0xd7, 0xd9, 0x1a, 0x06, 0xae, 0xb3, 0xef, 0x3b, 0x19, 0x14, 0x2f,
	0xa0, 0xb3, 0x7e, 0x70, 0x80, 0xdb, 0x8a, 0xd9, 0x1e, 0xcf, 0x45, 0x48, 0xfe, 0x7c, 0xec, 0xc5,
	0xb2, 0xa9, 0xf1, 0xf7, 0x34, 0xca, 0x08, 0x12, 0x7d, 0xe8, 0x2c, 0x94, 0xb2, 0x7e, 0x41, 0x48,
	0xa1, 0xb6, 0x6e, 0x5f, 0x40, 0x61, 0x0f, 0x82, 0x75, 0x96, 0x12, 0xed, 0x3e, 0x05, 0x45, 0x16,
	0x75, 0x30, 0x90, 0x1f, 0x78, 0xa6, 0x38, 0x85, 0xf6, 0x24, 0x4d, 0xbd, 0x56, 0x21, 0x46, 0x57,
	0xfb, 0x8d, 0x21, 0x85, 0x28, 0x42, 0x3d, 0x49, 0x94, 0x50, 0xbe, 0x63, 0xb6, 0xe2, 0x1c, 0x4e,
	0x66, 0x7a, 0x13, 0xe7, 0x53, 0xc3, 0x5d, 0xff, 0x41, 0xb8, 0x54, 0x37, 0xba, 0x52, 0x53, 0xc3,
	0x44, 0xe4, 0x1b, 0x52, 0x5a, 0x0c, 0xa1, 0x3b, 0x57, 0xd5, 0xbd, 0xb6, 0x87, 0x92, 0xd9, 0x9f,
	0x79, 0xf6, 0x35, 0x2a, 0x7f, 0x3f, 0x55, 0x38, 0x09, 0x5b, 0xd3, 0x94, 0x67, 0xba, 0xa3, 0x67,
	0xe3, 0xb5, 0x29, 0x58, 0x39, 0x3e, 0x9a, 0x20, 0xca, 0x65, 0xc5, 0xa1, 0xe4, 0xd7, 0xaa, 0x73,
	0x08, 0x61, 0x6e, 0xee, 0x38, 0xd7, 0x6f, 0xc5, 0x39, 0x82, 0xe4, 0x67, 0x9e, 0x49, 0x8b, 0x6a,
	0xf2, 0x7f, 0x29, 0xc8, 0x92, 0x05, 0x4d, 0xc9, 0x48, 0x3f, 0xbc, 0xdf, 0xaf, 0xf8, 0x97, 0xfb,
	0x25, 0xd3, 0x40, 0x0d, 0x67, 0xe3, 0xd5, 0x3d, 0x57, 0xf6, 0x9e, 0x0c, 0x18, 0xca, 0xb8, 0x76,
	0x1d, 0xfa, 0xf2, 0x72, 0x67, 0x58, 0x21, 0xf6, 0xa5, 0x03, 0xc4, 0xff, 0xd0, 0xfb, 0x7a, 0x93,
	0xa8, 0x34, 0x55, 0x29, 0xe6, 0x5b, 0xe4, 0xaa, 0x01, 0x74, 0x67, 0x5a, 0x9b, 0x24, 0xde, 0x1c,
	0xfc, 0xcb, 0x88, 0x08, 0xda, 0xd7, 0xa5, 0xd9, 0x3a, 0x9e, 0xd8, 0x0f, 0xbe, 0x1f, 0x11, 0xf9,
	0x89, 0x06, 0xe3, 0xbd, 0x13, 0x6f, 0xca, 0xbe, 0x90, 0x10, 0xce, 0x55, 0xb6, 0xdb, 0x27, 0xda,
	0xd6, 0xb6, 0x3c, 0xaf, 0xdf, 0x84, 0x61, 0xf9, 0xab, 0x51, 0x83, 0x24, 0xe6, 0xea, 0xa1, 0xfa,
	0xa6, 0xcd, 0x4a, 0xe5, 0x5b, 0xb6, 0xb6, 0x3b, 0x0b, 0x55, 0x63, 0xa3, 0x38, 0x4a, 0x5e, 0x80,
	0x49, 0xc9, 0xca, 0x5d, 0xc0, 0x33, 0xba, 0x6d, 0xa9, 0xb6, 0xb9, 0xda, 0x54, 0xda, 0x7e, 0xc9,
	0x33, 0x55, 0x54, 0x24, 0x65, 0x57, 0xbe, 0xf6, 0x84, 0xc9, 0x7c, 0x56, 0xc5, 0x2c, 0xce, 0xa0,
	0x61, 0x16, 0xaf, 0xe2, 0xa8, 0xfe, 0xf2, 0xc4, 0x2b, 0x00, 0xfa, 0xb5, 0xb0, 0xda, 0xd4, 0x56,
	0x1a, 0x34, 0xbe, 0x43, 0xc2, 0xe5, 0xfb, 0x66, 0x15, 0xbe, 0x13, 0xcf, 0xe3, 0x05, 0x67, 0x8f,
	0x1f, 0x32, 0xd2, 0xee, 0x27, 0xc7, 0xf4, 0xe7, 0xf1, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0xec, 0x60, 0xb7, 0x4a, 0x04, 0x00, 0x00,
}
