// Code generated by protoc-gen-go.
// source: vxlan.proto
// DO NOT EDIT!

/*
Package vxlan is a generated protocol buffer package.

It is generated from these files:
	vxlan.proto

It has these top-level messages:
	Vxlan
	Vxlan_
*/
package vxlan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// NLAN vxlan module
type Vxlan struct {
	Vxlan_           []*Vxlan_ `protobuf:"bytes,1,rep,name=Vxlan_" json:"Vxlan_,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Vxlan) Reset()         { *m = Vxlan{} }
func (m *Vxlan) String() string { return proto.CompactTextString(m) }
func (*Vxlan) ProtoMessage()    {}

func (m *Vxlan) GetVxlan_() []*Vxlan_ {
	if m != nil {
		return m.Vxlan_
	}
	return nil
}

type Vxlan_ struct {
	LocalIp          *string  `protobuf:"bytes,1,opt,name=LocalIp" json:"LocalIp,omitempty"`
	RemoteIps        []string `protobuf:"bytes,2,rep,name=RemoteIps" json:"RemoteIps,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vxlan_) Reset()         { *m = Vxlan_{} }
func (m *Vxlan_) String() string { return proto.CompactTextString(m) }
func (*Vxlan_) ProtoMessage()    {}

func (m *Vxlan_) GetLocalIp() string {
	if m != nil && m.LocalIp != nil {
		return *m.LocalIp
	}
	return ""
}

func (m *Vxlan_) GetRemoteIps() []string {
	if m != nil {
		return m.RemoteIps
	}
	return nil
}
