// Code generated by protoc-gen-go.
// source: subnets.proto
// DO NOT EDIT!

/*
Package subnets is a generated protocol buffer package.

It is generated from these files:
	subnets.proto

It has these top-level messages:
	Subnets
	Subnets_
	IpDvr
*/
package subnets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// NLAN subnets module
type Subnets struct {
	Subnets_         []*Subnets_ `protobuf:"bytes,1,rep,name=Subnets_" json:"Subnets_,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Subnets) Reset()         { *m = Subnets{} }
func (m *Subnets) String() string { return proto.CompactTextString(m) }
func (*Subnets) ProtoMessage()    {}

func (m *Subnets) GetSubnets_() []*Subnets_ {
	if m != nil {
		return m.Subnets_
	}
	return nil
}

type Subnets_ struct {
	IpDvr            []*IpDvr `protobuf:"bytes,1,rep,name=IpDvr" json:"IpDvr,omitempty"`
	Peers            []string `protobuf:"bytes,2,rep,name=Peers" json:"Peers,omitempty"`
	Ports            []string `protobuf:"bytes,3,rep,name=Ports" json:"Ports,omitempty"`
	Vid              *uint32  `protobuf:"varint,4,opt,name=Vid" json:"Vid,omitempty"`
	Vni              *uint32  `protobuf:"varint,5,opt,name=Vni" json:"Vni,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Subnets_) Reset()         { *m = Subnets_{} }
func (m *Subnets_) String() string { return proto.CompactTextString(m) }
func (*Subnets_) ProtoMessage()    {}

func (m *Subnets_) GetIpDvr() []*IpDvr {
	if m != nil {
		return m.IpDvr
	}
	return nil
}

func (m *Subnets_) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Subnets_) GetPorts() []string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Subnets_) GetVid() uint32 {
	if m != nil && m.Vid != nil {
		return *m.Vid
	}
	return 0
}

func (m *Subnets_) GetVni() uint32 {
	if m != nil && m.Vni != nil {
		return *m.Vni
	}
	return 0
}

type IpDvr struct {
	Addr             *string `protobuf:"bytes,1,opt,name=Addr" json:"Addr,omitempty"`
	Dhcp             *string `protobuf:"bytes,2,opt,name=Dhcp" json:"Dhcp,omitempty"`
	Mode             *string `protobuf:"bytes,3,opt,name=Mode" json:"Mode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IpDvr) Reset()         { *m = IpDvr{} }
func (m *IpDvr) String() string { return proto.CompactTextString(m) }
func (*IpDvr) ProtoMessage()    {}

func (m *IpDvr) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *IpDvr) GetDhcp() string {
	if m != nil && m.Dhcp != nil {
		return *m.Dhcp
	}
	return ""
}

func (m *IpDvr) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}
